In [1]:
from __future__ import print_function
import torch

In [2]:
x=torch.Tensor(5,3)
print(x)


 0.0000e+00  0.0000e+00  3.2763e+15
 4.5604e-41  3.2573e+15  4.5604e-41
 1.5290e-38  0.0000e+00  1.5290e-38
 0.0000e+00  3.1260e+22  4.5604e-41
 3.0396e+22  4.5604e-41  1.1002e-31
[torch.FloatTensor of size 5x3]



In [3]:
x=torch.rand(5,3)
print(x)


 0.2120  0.3738  0.5253
 0.2827  0.5104  0.9682
 0.4403  0.5703  0.6925
 0.6888  0.5142  0.8773
 0.8248  0.8457  0.4116
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y=torch.rand(5,3)
print(x+y)


 0.3220  0.7699  1.2280
 1.2157  1.0703  1.2906
 1.3711  1.5080  1.6085
 1.3502  0.8339  1.8519
 1.5811  1.0951  0.6073
[torch.FloatTensor of size 5x3]



In [6]:
print(torch.add(x,y))


 0.3220  0.7699  1.2280
 1.2157  1.0703  1.2906
 1.3711  1.5080  1.6085
 1.3502  0.8339  1.8519
 1.5811  1.0951  0.6073
[torch.FloatTensor of size 5x3]



In [7]:
result=torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)


 0.3220  0.7699  1.2280
 1.2157  1.0703  1.2906
 1.3711  1.5080  1.6085
 1.3502  0.8339  1.8519
 1.5811  1.0951  0.6073
[torch.FloatTensor of size 5x3]



In [8]:
#替换原张量
y.add_(x)
print(y)


 0.3220  0.7699  1.2280
 1.2157  1.0703  1.2906
 1.3711  1.5080  1.6085
 1.3502  0.8339  1.8519
 1.5811  1.0951  0.6073
[torch.FloatTensor of size 5x3]



In [9]:
print(x[:,1])


 0.3738
 0.5104
 0.5703
 0.5142
 0.8457
[torch.FloatTensor of size 5]



In [10]:
a=torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b=a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [14]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [15]:
torch.add(b,1,out=b)
print(a)
print(b)

[ 3.  3.  3.  3.  3.]

 3
 3
 3
 3
 3
[torch.DoubleTensor of size 5]

